data_sources:
  xilinx:
    name: "xilinx"
    type: "web_scraping"
    strategy: "selenium"
    base_url: "https://docs.amd.com/search/all"
    rate_limit: 2
    max_results: 1  # 取得する最大件数
    scroll_pages: 10   # スクロールするページ数
    load_more_attempts: 5  # 「もっと見る」ボタンのクリック試行回数
    scroll_delay: 2   # スクロール後の待機時間（秒）
    page_load_timeout: 30  # ページ読み込みタイムアウト（秒）
    element_wait_timeout: 10  # 要素待機タイムアウト（秒）
    # ブラウザー設定
    browser:
      type: "chrome"  # "chrome" または "firefox"
      headless: true
      # chromedriver_path: "C:/path/to/chromedriver.exe"  # 手動パス指定
      # geckodriver_path: "C:/path/to/geckodriver.exe"    # 手動パス指定
    search_params:
      query: "versal"  # URLの query= パラメータと一致
      document_types: ["Data Sheet", "User Guides & Manuals"]
      product_types: ["IP Cores (Adaptive SoC & FPGA)"]
      date_filter: "last_month"
      content_lang: "en-US"
  
  altera:
    name: "altera"
    type: "web_scraping"
    strategy: "selenium"
    base_url: "https://www.intel.com/content/www/us/en/products/details/fpga/stratix/10/docs.html"
    rate_limit: 2
    max_results: 1  # 取得する最大件数
    scroll_pages: 10   # スクロールするページ数
    load_more_attempts: 5  # 「もっと見る」ボタンのクリック試行回数
    scroll_delay: 2   # スクロール後の待機時間（秒）
    page_load_timeout: 30  # ページ読み込みタイムアウト（秒）
    element_wait_timeout: 10  # 要素待機タイムアウト（秒）
    # ブラウザー設定
    browser:
      type: "firefox"  # "chrome" または "firefox"
      headless: true
      # chromedriver_path: "C:/path/to/chromedriver.exe"  # 手動パス指定
      # geckodriver_path: "C:/path/to/geckodriver.exe"    # 手動パス指定
    search_params:
      query: "DSP"  # URLの q= パラメータと一致
      sort: "Relevancy"
  
  arxiv:
    name: "arxiv"
    type: "api"
    base_url: "http://export.arxiv.org/api/query"
    rate_limit: 1
    max_results: 1  # 各カテゴリから取得する最大件数
    categories: ["cs.AR", "cs.AI"]  # Hardware Architecture, Artificial Intelligence
    enable_diff: true  # 差分取得機能を有効化
    sort_by: "lastUpdatedDate"
    sort_order: "descending"

# デフォルトブラウザー設定（グローバル）
default_browser:
  type: "chrome"  # "chrome" または "firefox"
  headless: true
  options:
    chrome:
      - "--no-sandbox"
      - "--disable-dev-shm-usage"
      - "--disable-gpu"
      - "--window-size=1920,1080"
      - "--disable-blink-features=AutomationControlled"
    firefox:
      - "--no-sandbox"
      - "--disable-dev-shm-usage"
      - "--disable-extensions"
  # カスタムドライバーパス（オプション）
  # chromedriver_path: "C:/path/to/chromedriver.exe"
  # geckodriver_path: "C:/path/to/geckodriver.exe"

# 通知設定
notifications:
  email:
    enabled: true
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    recipients_file: "config/recipients.yaml"
    credentials_file: "config/email_credentials.yaml"
  
# 出力設定
output:
  json_file: "results/fpga_documents.json"
  create_backup: true
  
# ログ設定
logging:
  level: "INFO"
  file: "logs/scraper.log"
  max_size: "10MB"
  backup_count: 5

# クリーンアップ設定
cleanup:
  keep_days: 7  # 保持する日数（デフォルト：7日）
  enabled: true  # クリーンアップ機能を有効化
  file_types: ["*.json", "*.backup_*", "*.log", "*.txt"]  # 削除対象のファイルタイプ

# LLM統合設定（pip-installed LocalLLM - ✅ 問題解決済み）
llm_integration:
  enabled: true  # LocalLLM要約機能を有効化
  package_installed: true  # pip install済みLocalLLMを使用
  issue_resolved: true  # GitHub Issue #1 解決済み
  package_source: "pip"  # pip install経由
  summary_config:
    language: "ja"  # 出力言語（ja=日本語, en=英語）
    summary_type: "detailed"  # 要約タイプ（brief, detailed, academic, concise）
    max_length: 2000  # 最大文字数
    output_format: "markdown"  # 出力形式
    individual_processing: true  # 個別URL処理
    include_urls: true  # URL情報を含める
    batch_size: 5  # バッチサイズ
    enable_translation: true  # 英日翻訳を有効化
    translation_chunk_size: 4000  # 翻訳チャンクサイズ
    retry_count: 3  # リトライ回数
    timeout: 600  # タイムアウト（秒）
  focus_areas:  # 重点分析領域
    - "key_findings"
    - "document_categories" 
    - "source_comparison"
    - "technical_insights"
